"""
Gravity Search — Agent Base Classes
Foundation for the Hebbia-style multi-agent architecture.

Every agent:
  1. Accepts an AgentContext (shared state across the pipeline)
  2. Returns an AgentResult (output + trace log for transparency)
  3. Logs every action with timestamps for full traceability
"""

from __future__ import annotations

import time
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

import structlog

logger = structlog.get_logger()


# ── Shared Context passed between agents ────────────────────────────────

@dataclass
class AgentContext:
    """Mutable state that flows through the agent pipeline."""

    # Original user query
    query: str

    # Query understanding output (from existing QueryUnderstanding)
    query_plan: dict = field(default_factory=dict)

    # Sub-tasks generated by the Planner
    sub_tasks: list[SubTask] = field(default_factory=list)

    # Retrieved passages per sub-task (populated by Reader agents)
    retrieved_passages: dict[str, list] = field(default_factory=dict)

    # Extracted structured facts (populated by Extractor)
    extracted_facts: list[dict] = field(default_factory=list)

    # Critic feedback (populated by Critic agent)
    critic_feedback: CriticFeedback | None = None

    # Final synthesized output (populated by Writer)
    final_answer: str = ""
    final_citations: list[dict] = field(default_factory=list)
    structured_data: list[dict] = field(default_factory=list)
    chart_specs: list[dict] = field(default_factory=list)

    # Pipeline metadata
    trace_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    iteration: int = 0
    max_iterations: int = 2
    total_cost_usd: float = 0.0

    # Verification results (populated by VerifierAgent — Fin-R1 paper)
    verification_results: dict | list = field(default_factory=dict)

    # Full trace log for transparency
    trace_log: list[TraceEntry] = field(default_factory=list)

    def add_trace(self, agent: str, action: str, detail: str = "", duration_ms: float = 0):
        """Append a trace entry — every agent action is logged."""
        entry = TraceEntry(
            agent=agent,
            action=action,
            detail=detail,
            duration_ms=round(duration_ms, 1),
            timestamp=time.time(),
            iteration=self.iteration,
        )
        self.trace_log.append(entry)
        logger.info(
            "agent_trace",
            trace_id=self.trace_id,
            agent=agent,
            action=action,
            detail=detail[:200],
            duration_ms=round(duration_ms, 1),
            iteration=self.iteration,
        )


@dataclass
class TraceEntry:
    """One action in the agent trace — shown to the user for transparency."""
    agent: str
    action: str
    detail: str = ""
    duration_ms: float = 0
    timestamp: float = 0
    iteration: int = 0


@dataclass
class SubTask:
    """A decomposed sub-question from the Planner."""
    id: str
    question: str
    retrieval_strategy: str = "all"        # "dense" | "bm25" | "splade" | "graph" | "structured" | "all"
    target_companies: list[str] = field(default_factory=list)
    target_periods: list[str] = field(default_factory=list)
    expected_output: str = "narrative"     # "narrative" | "table" | "number"
    priority: int = 1                       # 1=highest


@dataclass
class CriticFeedback:
    """Quality assessment from the Critic agent."""
    quality_score: float            # 0.0 → 1.0
    is_sufficient: bool
    coverage_gaps: list[str] = field(default_factory=list)
    unsupported_claims: list[str] = field(default_factory=list)
    contradiction_flags: list[str] = field(default_factory=list)
    retry_guidance: str = ""        # Instructions for the Planner on what to fix


# ── Agent ABC ───────────────────────────────────────────────────────────

class BaseAgent(ABC):
    """Abstract base class for all pipeline agents."""

    name: str = "BaseAgent"

    @abstractmethod
    async def execute(self, ctx: AgentContext) -> AgentContext:
        """
        Run this agent's logic, mutating and returning the context.
        Every agent must:
          1. Read what it needs from ctx
          2. Do its work (LLM calls, retrieval, etc.)
          3. Write results back to ctx
          4. Add trace entries via ctx.add_trace(...)
        """
        ...

    async def _timed(self, ctx: AgentContext, action: str, coro):
        """Helper: run an async operation and log its duration."""
        t0 = time.perf_counter()
        result = await coro
        elapsed = (time.perf_counter() - t0) * 1000
        ctx.add_trace(self.name, action, duration_ms=elapsed)
        return result, elapsed
